# Alembic migration script template
"""add fields to adoption model

Revision ID: 72b7b3cc1c38
Revises: d36f3e2f2e5e
Create Date: 2025-11-26 00:14:46.592066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72b7b3cc1c38'
down_revision = 'd36f3e2f2e5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adoptions', sa.Column('breed', sa.String(length=100), nullable=True))
    op.add_column('adoptions', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('adoptions', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('adoptions', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adoptions', 'email')
    op.drop_column('adoptions', 'phone')
    op.drop_column('adoptions', 'gender')
    op.drop_column('adoptions', 'breed')
    # ### end Alembic commands ###
